# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build and push a new release to the App Store"
  lane :release do
    match(type: "appstore") # This will use existing profiles and certificates from the repo
    build_app(
      scheme: "Runner", # Replace with your Xcode scheme
      export_method: "app-store", # Ensure export method matches your needs
      app_identifier: "com.xnuvers007.yogathewitchstore" # Replace with your app's bundle identifier
    )
    upload_to_app_store # Upload the app to the App Store
  end
end
